training_loc: cluster

name: ResAllStart

resnet: 18

paths:
  output: /netscratch/schiesser/embed_then_cat/runs/
  dataset: /netscratch/schiesser/inet/
  train: imagenet21k-train.msgpack
  test: imagenet21k-test.msgpack
  visnet_weights: /netscratch/schiesser/embed_then_cat/vit_triplet_imagenet.pth

model:
  nheads: 8
  nlayers: 4

optimizer:
  lr_initial: 5e-4
  lr_target: 5e-5
  epochs: 600
  weight_decay: 1e-5
  log_step: 10
  epsilon: 0.1
  acc_steps: 1

dataloader:
  num_samples: 10000
  batch_size: 16
  num_classes: 10
  num_images: 5
  train_ratio: 0.01
  test_ratio: 1
  num_workers: 16

resample: 10