training_loc: "local"

resnet: 18

paths:
  output: output/
  dataset: /Volumes/DFKI117/

model:
  nheads: 4
  nlayers: 8

optimizer:
  lr_initial: 0.000001
  lr_target: 0.0000001
  lr: 0.001
  epochs: 40
  weight_decay: 0.00001
  log_step: 500
  epsilon: 0.1
  acc_steps: 8

dataloader:
  num_samples: 10000
  batch_size: 16
  num_classes: 5
  num_images: 10