training_loc: "local"

paths:
  output: output/
  dataset: data/


model:
  lr: 0.001
  weight_decay: 0.00001
  epochs: 40
  log_step: 500

dataloader:
  num_samples: 10000
  batch_size: 16
  num_classes: 4