training_loc:

resnet: 

name: 

paths:
  output:
  dataset:

model:
  nheads:
  nlayers:

optimizer:
  lr_initial:
  lr_target:
  lr:
  epochs:
  weight_decay:
  log_step:
  epsilon:
  acc_steps:

dataloader:
  num_samples:
  batch_size:
  num_classes:
  num_images:
