training_loc:

name: 

encoder: 

paths:
  output:
  dataset:
  train:
  test:
  visnet_weights:
  class_index:

model:
  nheads:
  nlayers:

optimizer:
  epochs:
  weight_decay:
  log_step:
  epsilon:
  acc_steps:
  lr_encoder:
  lr_rest:
  lr_schedule:
  lr_initial: # lr_max
  lr_target: # lr_min

dataloader:
  num_samples:
  batch_size:
  num_classes:
  num_images:
  train_ratio: 
  test_ratio:
  num_workers:
